[env]
PATH = "{{env.PATH}}"
# Load env from the dotenv file after tools have defined environment variables
_.file = { path = ".env", tools = true }

[tools]
go = "1.24.8"
node = "20"

[tasks.go-test]
run = "go test ./... -v"

[tasks.frontend-install]
dir = "frontend"
run = "npm install"

[tasks.frontend-build]
dir = "frontend"
run = "npm run build"
depends = ["frontend-install"]

[tasks.frontend-dev]
dir = "frontend"
run = "npm run dev"
depends = ["frontend-install"]

[tasks.backend-dev]
run = "go run ./cmd/nomad-compass"
